# Generated by Django 2.0.4 on 2018-04-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_westudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='westudent',
            name='age',
            field=models.IntegerField(),
        ),
    ]
