# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mystudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('sex', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
